// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqgekoejxcuadxvynkvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxZ2Vrb2VqeGN1YWR4dnlua3Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5OTY1NjMsImV4cCI6MjA2NDU3MjU2M30.muWOjAmuPuei81PdGQwdKO2qpvV3zTs1OxBEANzCnB0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);